eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/


microservice:
  payment-service:
    endpoints:
      fetchPaymentById:
        uri: http://PAYMENT-SERVICE/payments/
  user-service:
    endpoints:
      fetchUserById:
        uri: http://USER-SERVICE/users/   
        
        
test:
  input: 500000    

#configurations used Elastic Search ,Logstash,kibana for generating  logs during  Api's Request From PostMan
#logging:
  #file:
    #name: D:\app-logs\ecom-log
